{
 "title": "HLF / Ledger and Consensus",
 "tags": [
  "hlf",
  "ledger",
  "consensus",
  "smartbft"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ledger Base Information",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
     "targets": [
      { "expr": "fabric_version", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Ledger Channel And Chaincodes",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "ledger_transaction_count{validation_code =\"VALID\", transaction_type = \"ENDORSER_TRANSACTION\"}[1m]",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Consensus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "SmartBFT Consensus Cluster Size",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "consensus_smartbft_cluster_size",
       "legendFormat": "{{channel}} {{id}}"
      }
     ]
    },
    {
     "title": "SmartBFT Consensus Leader ID",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2 },
     "targets": [
      { "expr": "consensus_smartbft_leader_id", "legendFormat": "{{channel}} {{id}}" }
     ]
    },
    {
     "title": "SmartBFT Is Leader",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
     "targets": [
      { "expr": "consensus_smartbft_is_leader", "legendFormat": "{{channel}} {{id}}" }
     ]
    },
    {
     "title": "SmartBFT Is Leader Over Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg_over_time(consensus_smartbft_is_leader[$__range])",
       "legendFormat": "{{channel}} {{id}}"
      }
     ]
    },
    {
     "title": "SmartBFT Commited Block Number",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "consensus_smartbft_committed_block_number",
       "legendFormat": "{{channel}} {{id}}"
      }
     ]
    },
    {
     "title": "SmartBFT Commited Block Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(consensus_smartbft_committed_block_number{}[$__rate_interval])",
       "legendFormat": "{{channel}} {{id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Endorser",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Endorser Proposal Time Distribution by rate",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum by (le) (rate(endorser_proposal_duration_bucket{}[$__range]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Endorser Proposals Simulation Failures rate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "recps" } },
     "targets": [
      {
       "expr": "rate(endorser_proposal_simulation_failures{}[$__rate_interval])",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Endorser Successful Proposals rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "recps" } },
     "targets": [
      {
       "expr": "rate(endorser_successful_proposals{}[$__rate_interval])",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Endorser Proposals Received rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "recps" } },
     "targets": [
      {
       "expr": "rate(endorser_proposals_received{}[$__rate_interval])",
       "legendFormat": "{{id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Chaincode",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ledger Shim Requests Compleated rate",
     "type": "timeseries",
     "description": "Rate of chaincode shim requests completed.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "recps" } },
     "targets": [
      {
       "expr": "rate(chaincode_shim_requests_completed{}[$__rate_interval])",
       "legendFormat": "{{type}} {{id}} {{channel}} {{chaincode}}"
      }
     ]
    },
    {
     "title": "Ledger Shim Requests  Received rate",
     "type": "timeseries",
     "description": "Rate of chaincode shim requests completed.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "recps" } },
     "targets": [
      {
       "expr": "rate(chaincode_shim_requests_received{}[$__rate_interval])",
       "legendFormat": "{{type}} {{id}} {{channel}} {{chaincode}}"
      }
     ]
    },
    {
     "title": "Chaincode Shim Request rate by time distribution",
     "type": "heatmap",
     "description": "Распределение по времени средней скорости исполнения shim запросов. Чем выше и краснее тем хуже. Это означает что больше запросов в секунду исполняются за длительное время.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum by (le) (rate(chaincode_shim_request_duration_bucket{}[$__range]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Chaincode Total Time Spend Over Interval by type",
     "type": "timeseries",
     "description": "Rate of chaincode shim requests completed.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (type,channel,id) (delta(chaincode_shim_request_duration_sum{}[$__rate_interval]))",
       "legendFormat": "{{type}} {{id}} {{channel}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ledger",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ledger Blockchain Height",
     "type": "timeseries",
     "description": "Height of the chain in blocks.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
     "targets": [
      { "expr": "ledger_blockchain_height", "legendFormat": "{{id}} {{channel}}" }
     ]
    },
    {
     "title": "Ledger Blockchain Height rate",
     "type": "timeseries",
     "description": "Rate of height of the chain in blocks.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "recps" } },
     "targets": [
      {
       "expr": "rate(ledger_blockchain_height{}[$__rate_interval])",
       "legendFormat": "{{id}} {{channel}}"
      }
     ]
    },
    {
     "title": "Ledger Transaction In Valid state rate",
     "type": "timeseries",
     "description": "Rate of ledger transaction",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "recps" } },
     "targets": [
      {
       "expr": "rate(ledger_transaction_count{validation_code = \"VALID\"}[$__rate_interval])",
       "legendFormat": "{{id}} {{channel}} {{chaincode}} "
      }
     ]
    },
    {
     "title": "Ledger Transaction Failed State rate",
     "type": "timeseries",
     "description": "Rate of ledger transaction",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "recps" } },
     "targets": [
      {
       "expr": "rate(ledger_transaction_count{validation_code != \"VALID\"}[$__rate_interval])",
       "legendFormat": "{{id}} {{channel}} {{chaincode}} {{validation_code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log Entries Writen rate",
     "type": "timeseries",
     "description": "Rate of log entries that are written",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "rate(logging_entries_written{}[$__rate_interval])",
       "legendFormat": "{{id}} {{level}}"
      }
     ]
    },
    {
     "title": "Log Entries Checked rate",
     "type": "timeseries",
     "description": "Rate of log entries checked against the active logging level",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "rate(logging_entries_checked{}[$__rate_interval])",
       "legendFormat": "{{id}} {{level}}"
      }
     ]
    }
   ]
  }
 ]
}