{
 "title": "HLF / Robot",
 "tags": [
  "hlf",
  "robot",
  "batch",
  "swap"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "robot_app_info" } },
   {
    "name": "robot",
    "query": {
     "query": "label_values(robot_height_ledger_blocks,robot)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Robot Init Duration",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "robot_app_init_duration_seconds{instance=~\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Robot General Information",
     "type": "table",
     "gridPos": { "h": 5, "w": 9, "x": 3, "y": 1 },
     "targets": [
      {
       "expr": "robot_app_info{instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Robot Stopped With Errors",
     "type": "timeseries",
     "description": "Количество go рутин роботов которые  были остановлены с ошибками. Метрика должна стремиться к 0 в нормальных условиях.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum(rate(robot_robot_stopped_total{instance=~\"$instance\",iserr=\"true\",robot=~\"$robot\"}[$__rate_interval])) by (robot,instance)",
       "legendFormat": "{{instance}} {{robot}}"
      }
     ]
    },
    {
     "title": "Robot TX waiting process count",
     "type": "timeseries",
     "description": "amount of transactions (counts everything that is in a batch - transaction ids, swaps, multiswaps, keys of swaps and keys of multiswaps) awaiting execution when collector added them into a queue",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "robot_tx_waiting_process_count{instance=~\"$instance\"}",
       "legendFormat": "{{instance}} {{ channel }} {{ robot }}"
      }
     ]
    },
    {
     "title": "Robots stopped ",
     "type": "timeseries",
     "description": "Количество go рутин роботов которые  были остановлены без ошибок. Метрика должна стремиться к 0 в нормальных условиях.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "sum(rate(robot_robot_stopped_total{instance=~\"$instance\",iserr=\"false\",robot=~\"$robot\"}[$__rate_interval])) by (robot,instance)",
       "legendFormat": "{{instance}} {{robot}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Robot Height Ledger Blocks",
     "type": "timeseries",
     "description": " ledger's block num where batch was committed. Takes after every executeBatch",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "robot_height_ledger_blocks{instance=~\"$instance\", robot=~\"$robot\"}",
       "legendFormat": "{{ instance }} {{ robot }}"
      }
     ]
    },
    {
     "title": "Robot Height Ledger Blocks Rate",
     "type": "timeseries",
     "description": " ledger's block rate where batch was committed. Takes after every executeBatch",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(robot_height_ledger_blocks{instance=~\"$instance\", robot=~\"$robot\"}[$__rate_interval])",
       "legendFormat": "{{ instance }} {{ robot }}"
      }
     ]
    },
    {
     "title": "Batches execute",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "robot_batches_executed_total{instance=~\"$instance\",robot=~\"$robot\"}",
       "legendFormat": "{{instance}} {{robot}}"
      }
     ]
    },
    {
     "title": "Batches Execute Rate",
     "type": "timeseries",
     "description": "Количество блоков обработанных роботом",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(robot_batches_executed_total{instance=~\"$instance\", robot=~\"$robot\"}[$__rate_interval])",
       "legendFormat": "{{ instance }} {{ robot }}"
      }
     ]
    },
    {
     "title": "Batches executed errors",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "sum(rate(robot_batches_executed_total{instance=~\"$instance\",iserr=\"true\"}[$__rate_interval])) by (instance,robot)",
       "legendFormat": "{{instance}} {{ robot }}"
      }
     ]
    },
    {
     "title": "Batch execute duration seconds  95 percentille",
     "type": "timeseries",
     "description": "Batch collects by asking collectors. Batch is ready when one of the batch limits on the number of transactions, size or timeout occurs",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, rate(robot_batch_execute_duration_seconds_bucket{instance=~\"$instance\",robot=~\"$robot\"}[$__rate_interval]))",
       "legendFormat": "{{instance}} {{ robot }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Timings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Amount of times request size was exceeded during executeBatch",
     "type": "timeseries",
     "description": "Labels:\nrobot - robot's destination channel\nis_first_attempt - whether it is a first attempt or not - true, false ",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum(rate(robot_ord_reqsize_exceeded_total{instance=~\"$instance\"}[$__rate_interval])) by (robot, is_first_attempt)",
       "legendFormat": "{{instance}} {{ robot }} is_first_attempt={{ is_first_attempt }}"
      }
     ]
    },
    {
     "title": "Amount of times there was an error on creating HLF events source",
     "type": "timeseries",
     "description": "Labels:\nrobot - robot's destination channel\nchannel - robot's source channel\nis_first_attempt - whether it is a first attempt or not - true, false\nis_src_ch_closed - whether source channel was closed or not - true, false\nis_timeout - whether await timeout was reached - true, false",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "sum(rate(robot_src_channel_errors_total{instance=~\"$instance\"}[$__rate_interval])) by (instance,robot, channel, is_first_attempt, is_src_ch_closed, is_timeout )",
       "legendFormat": "{{instance}} {{channel}} {{ robot}} {{ is_first_attempt}} {{ is_src_ch_closed}} {{ is_timeout }}"
      }
     ]
    },
    {
     "title": "Batch Collect Duration Seconds 95 percentille",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(robot_batch_collect_duration_seconds_bucket{instance=~\"$instance\"}[$__rate_interval])) by (instance,le, robot))",
       "legendFormat": "{{instance}} {{robot}}"
      }
     ]
    },
    {
     "title": "Collector process block num",
     "type": "timeseries",
     "description": "the block number processing by the collector",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "sum(rate(robot_collector_process_block_num{instance=~\"$instance\"}[$__rate_interval])) by (instance,channel)",
       "legendFormat": "{{instance}} {{channel}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Batch size total",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(robot_batch_size_bytes_total{instance=~\"$instance\"}[$__rate_interval])) by (instance,robot)",
       "legendFormat": "{{instance}} {{ robot }}"
      }
     ]
    },
    {
     "title": "Batch Size Estimated Diff 95 percentille",
     "type": "timeseries",
     "description": "Relative difference between real and assumed batch size",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, robot_batch_size_estimated_diff_bucket{instance=~\"$instance\"})",
       "legendFormat": "{{instance}} {{robot}}"
      }
     ]
    },
    {
     "title": "Amount of executed transactions (in all executed batches) ",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "sum(rate(robot_tx_executed_total{instance=~\"$instance\"}[$__rate_interval])) by (instance,robot, txtype)",
       "legendFormat": "{{instance}} {{ robot }} {{ txtype }}"
      }
     ]
    },
    {
     "title": "Batches executed total",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(robot_batches_executed_total{instance=~\"$instance\",iserr=\"false\"}[$__rate_interval])) by (instance,robot) ",
       "legendFormat": "{{instance}} {{ robot }}"
      }
     ]
    },
    {
     "title": "Block Tx Count 95 percentille",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(robot_block_tx_count_bucket{instance=~\"$instance\", robot=~\"$robot\"}[$__rate_interval])) by (instance,le, channel))",
       "legendFormat": "{{instance}} {{channel}}"
      }
     ]
    },
    {
     "title": "Batch Size 95 percentille",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, rate(robot_batch_size_bytes_bucket{instance=~\"$instance\",robot=~\"$robot\"}[$__rate_interval]))",
       "legendFormat": "{{instance}} {{ robot }}"
      }
     ]
    },
    {
     "title": "Batch TX count 95 percentille",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, rate(robot_batch_tx_count_bucket{instance=~\"$instance\",robot=~\"$robot\"}[$__rate_interval]))",
       "legendFormat": "{{instance}} {{ robot }}"
      }
     ]
    }
   ]
  }
 ]
}